name: allocator CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: install dependencies
        run: ./scripts/install_env.sh
        
      - name: build and test
        env:
          CC: ${{ matrix.compiler }}
        run: |
          make allocator
          make tests
